name: test::examples

on: push

jobs:
  files-changed:
    name: Detect File Changes - lint
    runs-on: ubuntu-latest
    outputs:
      lint: ${{ steps.filter.outputs.lint }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            lint:
              - '.github/workflows/**/*'
              - '**/*'

#  build:
#    if: needs.files-changed.outputs.frontend == 'true'
#    name: Build - Frontend
#    needs: files-changed
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7
#      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.0.3
#        with:
#          node-version-file: './.tool-versions'
#      - name: Frontend | Build
#        run: npm install && npm run build
#        working-directory: ./frontend

  lint-example-1-basic-map:
    if: needs.files-changed.outputs.lint == 'true'
    name: Lint Example 1 - Basic Map
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Lint
        run: npm install && npm run lint
        working-directory: ./examples/1-basic-map

  lint-example-2-static-layers:
    if: needs.files-changed.outputs.lint == 'true'
    name: Lint Example 2 - Static Layers
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Lint
        run: npm install && npm run lint
        working-directory: ./examples/2-static-layers

   lint-example-3-tags:
    if: needs.files-changed.outputs.lint == 'true'
    name: Lint Example 3 - Tags
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Lint
        run: npm install && npm run lint
        working-directory: ./examples/3-tags

#  unit:
#    if: needs.files-changed.outputs.frontend == 'true'
#    name: Unit - Frontend
#    needs: files-changed
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7
#      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.0.3
#        with:
#          node-version-file: './.tool-versions'
#      - name: Frontend | Unit
#        run: npm install && npm run test:unit
#        working-directory: ./frontend
