name: test:docs

on: push

jobs:
  files-changed:
    name: Detect File Changes - docs
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            docs:
              - '**/*.md'
              - 'LICENSE'

#  build:
#    if: needs.files-changed.outputs.frontend == 'true'
#    name: Build - Frontend
#    needs: files-changed
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7
#      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.0.3
#        with:
#          node-version-file: './.tool-versions'
#      - name: Frontend | Build
#        run: npm install && npm run build
#        working-directory: ./frontend

  docs:
    if: needs.files-changed.outputs.docs == 'true'
    name: Docs
    needs: files-changed
    runs-on: ubuntu-latest
    env:
      COVERAGE_REQUIRED: 0
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Docs
        run: |
          npm install
          npm run docs:generate
          ./scripts/docs-coverage.sh
        working-directory: ./